// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Wedding.Models;

namespace Wedding.Models.Migrations
{
    [DbContext(typeof(Ef))]
    [Migration("20180516040908_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("Wedding.Models.Invitee", b =>
                {
                    b.Property<int>("InviteeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AuthToken");

                    b.Property<DateTime?>("AuthTokenValidUntil");

                    b.Property<int>("Code");

                    b.Property<string>("Name");

                    b.HasKey("InviteeId");

                    b.ToTable("Invitees");
                });

            modelBuilder.Entity("Wedding.Models.Response", b =>
                {
                    b.Property<int>("ResponseId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Adults");

                    b.Property<bool>("BusFrom");

                    b.Property<bool>("BusTo");

                    b.Property<string>("Comments");

                    b.Property<string>("Dietary");

                    b.Property<bool>("Driving");

                    b.Property<int>("InviteeId");

                    b.Property<string>("MoochFrom")
                        .HasColumnType("nchar(2)");

                    b.Property<string>("MoochTo")
                        .HasColumnType("nchar(2)");

                    b.Property<bool>("WineTour");

                    b.HasKey("ResponseId");

                    b.HasIndex("InviteeId");

                    b.ToTable("Responses");
                });

            modelBuilder.Entity("Wedding.Models.ResponseOffer", b =>
                {
                    b.Property<int>("ResponseOfferId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("OfferCount");

                    b.Property<string>("OfferDay")
                        .HasColumnType("nchar(2)");

                    b.Property<int>("ResponseId");

                    b.HasKey("ResponseOfferId");

                    b.HasIndex("ResponseId");

                    b.ToTable("ResponseOffers");
                });

            modelBuilder.Entity("Wedding.Models.Response", b =>
                {
                    b.HasOne("Wedding.Models.Invitee", "Invitee")
                        .WithMany("Responses")
                        .HasForeignKey("InviteeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Wedding.Models.ResponseOffer", b =>
                {
                    b.HasOne("Wedding.Models.Response", "Response")
                        .WithMany("ResponseOffers")
                        .HasForeignKey("ResponseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
